FROM centos
MAINTAINER eivll0m@163.com

ENV ROOT_PASSWD passwd

RUN yum -y install openssh-server
RUN echo $ROOT_PASSWD |passwd --stdin root

RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key

CMD ["/usr/sbin/sshd","-D"]
EXPOSE 22
